### remember: docker swarm version on hostinger vps 
services:
  amiticia-site:
    image: node:20
    command: > 
      bash -c "
      cd /root 
      && git clone https://github.com/eusoubrasileiro/amitic-ai-core 
      && cd amitic-ai-core 
      && npm install 
      && npm run build 
      && npm run start"
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.5'
          memory: 500MB           
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=network_public"
        - "traefik.http.routers.amiticia.rule=Host(`amiticia.cc`,`www.amiticia.cc`)"
        - "traefik.http.routers.amiticia.entrypoints=websecure"
        - "traefik.http.routers.amiticia.priority=1"
        - "traefik.http.routers.amiticia.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.amiticia.service=amiticia"
        - "traefik.http.services.amiticia.loadbalancer.server.port=3000"

networks:
  network_public:
    external: true
    attachable: true
    name: network_public
